name: ViaBackwards
version: ${project.version}
description: Allow older Minecraft versions to connect to a newer server version.
main: nl.matsv.viabackwards.BukkitPlugin
api-version: 1.13

authors: [Matsv, KennyTV, Gerrygames, creeper123123321, ForceUpdate1]
website: ${project.url}

load: STARTUP
depend: [ViaVersion]
