name: ViaBackwards
version: ${version}
description: ${description}
main: com.viaversion.viabackwards.BukkitPlugin
api-version: 1.13
folia-supported: true

authors: [Matsv, kennytv, Gerrygames, creeper123123321, ForceUpdate1]
website: ${url}

depend: [ViaVersion]
